import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
buildscript {
    ext {
        kotlin_version = "2.4.10"
        corutines_version = "1.11.0"
        spring_boot_version = "3.5.16"
        telegrambots_version = "6.8.0"
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:$spring_boot_version")
    }
}
plugins {
    id "org.jetbrains.kotlin.jvm" version "$kotlin_version"
    id "org.jetbrains.kotlin.plugin.spring" version "$kotlin_version"
    id 'org.springframework.boot' version "$spring_boot_version"
    id "nebula.release" version "21.0.0"
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

ext {
}

dependencies {
    implementation platform("org.springframework.boot:spring-boot-dependencies:$spring_boot_version")

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$corutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:$corutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-reactor:$corutines_version"
    implementation 'io.github.oshai:kotlin-logging-jvm:8.0.4'
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-configuration-processor"
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation "com.github.ben-manes.caffeine:caffeine:3.2.4"
    implementation "org.springframework:spring-context-support"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin"
    implementation "org.telegram:telegrambots-spring-boot-starter:$telegrambots_version"
    implementation "org.telegram:telegrambotsextensions:$telegrambots_version"
    implementation 'org.apache.commons:commons-lang3:3.20.0'
    implementation "com.bucket4j:bucket4j_jdk17-core:8.19.0"
    implementation 'org.jsoup:jsoup:1.23.1'

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit5"
}

tasks.named('test') {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
}

tasks.register('distrib', Zip) {
    dependsOn bootJar
    def baseName = "${project.name}-${project.version}"

    into("$baseName/") {
        from('build/libs') {
            include "${baseName}.jar"
        }
        from("deploy/common")
    }

    def buildType = "snapshot"
    if (project.version.toString().matches("\\d+\\.\\d+\\.\\d+")) {
        buildType = "production"
    }

    into("$baseName/") {
        from("deploy/$buildType/") {
            include 'docker-compose.yml'
        }
    }
    into("$baseName/credentials") {
        from("deploy/$buildType/") {
            include '*.env'
        }
    }

    archiveFileName = provider { "${baseName}.zip" }
}

build.dependsOn(distrib)

tasks.withType(KotlinCompile).configureEach {
    compilerOptions {
        freeCompilerArgs.add('-Xjsr305=strict')
        jvmTarget = JvmTarget.JVM_25
    }
}
