#Web-server params
server:
  port: ${PORT:8080}

#Telegram params
telegram:
  chat-id: ${TG_CHANNEL_ID}
  bot:
    token: ${TG_BOT_TOKEN}
    name: ${TG_BOT_NAME}
  sending:
    ignore-error: false
    retry:
      max-attempts: 3
      delay: 10000
system:
  executor:
    core-size: 4
    max-size: 8
  #Main params
  work-dir: ${WORK_DIR}
  rate-limiting:
    enabled: true
    limits:
      - requests: 1
        period: 1m
      - requests: 25
        period: 1d
  timeouts:
    connect: 1s
    read: 2s
  retryer:
    maxAttempts: 3
    period: 100ms
    maxPeriod: 1s

spring:
  cache:
    cache-names: camera-snapshots-cache, road-conditions-cache
    caffeine:
      spec: expireAfterAccess=60s

road-conditions-external-service:
  url: 'https://www.cyprusski.com/piste-road-conditions'
live-camera:
  alias: 'jubileetroodos'
  stream-status:
    update-interval: 1h
    url: 'https://ipcamlive.com/player/getcamerastreamstate.php'
weather-provider:
  url: https://api.open-meteo.com/v1/forecast
  params:
    latitude: 34.93633979222953
    longitude: 32.864586572609916
    current: [temperature_2m,relative_humidity_2m,rain,showers,snowfall,snow_depth,weather_code,cloud_cover,wind_speed_10m,wind_gusts_10m]

#Logging params
logging:
  level:
    root: INFO
  file:
    name: ${WORK_DIR}/logs/cy-snow-telegram-bot.log
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB

