#Web-server params
server:
  port: ${PORT:8080}

#Telegram params
telegram:
  chat-id: ${TG_CHANNEL_ID}
  bot:
    token: ${TG_BOT_TOKEN}
    name: ${TG_BOT_NAME}
  sending:
    ignore-error: false
    retry:
      max-attempts: 3
      delay: 10000
system:
  executor:
    core-size: 4
    max-size: 8
  #Main params
  work-dir: ${WORK_DIR}
  rate-limiting:
    enabled: true
    limits:
      - requests: 1
        period: 1m
      - requests: 25
        period: 1d

feign:
  client:
    config:
      default:
        connectTimeout: 100
        readTimeout: 500
        loggerLevel: basic
        decode404: false
        retryer: com.anagorny.gpxanimatorbot.services.impl.RetryerImpl

#Logging params
logging:
  level:
    root: INFO
  file:
    name: ${WORK_DIR}/logs/cy-snow-telegram-bot.log
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB

